train:
  dataset_path: Pods:root=/mnt/data1/tensorflow_datasets/extracted/human_protein_atlas/Custom:split=train
  batch_size_per_gpu: 28
  output_dir: train_dir/proteinnet/baseline
  seed: 412
student:
  arch: prot_mamba_base
  patch_size: 8
  mlp_ratio: 4.0
  ffn_layer: "GatedMlp"
  num_tokens: 8
  num_register_tokens: 0
  # layerscale: 1.0
  # drop_path_rate: 0.3
teacher:
  warmup_teacher_temp: 0.01
  teacher_temp: 0.07
dino:
  head_mlp_bias: false
ibot:
  head_mlp_bias: false
