# this corresponds to the default config
train:
  dataset_path: Pods:root=/mnt/data1/tensorflow_datasets/extracted/human_protein_atlas/Custom:split=train
  batch_size_per_gpu: 64
  cache_dataset: true
  output_dir: train_dir/proteinnet/baseline
student:
  arch: prot_small
  ffn_layer: mlp
  mlp_ratio: 4.
